# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Set up Git user
      run: |
        git config --global user.name "Purbae16"
        git config --global user.email "purbahassan@gmail.com"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
      working-directory: ./todo_app
    - run: npm run build --if-present
      working-directory: ./todo_app
    - run: npm test
      working-directory: ./todo_app

  release:
    runs-on: ubuntu-latest
    needs: build 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Git user
      run: |
        git config --global user.name "Purbae16"
        git config --global user.email "purbahassan@gmail.com"
    - run: npm ci
      working-directory: ./todo_app
    - name: Release
      run: npx release-it --ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./todo_app
